---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false
  security:
    mock:
      users:
        - name: admin
          password: nimda
          roles:
            - Administrators
          additional:
            firstName: Syed
            lastName: Musthafa
            email: s.vahathbasha@sierradigitalinc.com
        - name: admin001
          password: nimda
          additional:
            firstName: Syed
            lastName: Ashif
            email: s.ashif@sierradigitalinc.com

